spring:
  application:
    name: /tiago-api
  security:
    user:
      name: admin
      password: password
server:
  port : 8080
  servlet:
    context-path: /tiago-api

google:
  application:
    name: Google Calendar Integration
  credentials:
    folderpath: credentials
    filename: "credentials.json"
  tokens:
    folder:
      path: tokens
  oauth:
    callback: http://localhost:8888/Callback

# telegram bot
bot:
  token: complete_me
  username: complete_me
  recieverid: 10

logging:
  level:
    root: info
