server:
  port : 8080
  servlet:
    context-path: /tiago-api

spring:
  application:
    name: /tiago-api
  security:
    user:
      name: admin
      password: password
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo

google:
  application:
    name: Google Calendar Integration
  credentials:
    folderpath: credentials
    filename: "credentials.json"
  tokens:
    folder:
      path: tokens
  oauth:
    callback: http://localhost:8888/Callback

# telegram bot
bot:
  token: complete_me
  username: complete_me
  recieverid: 10

logging:
  level:
    root: info
